### ISSUE TITLE
Problem of installing the Plugin Gatsby-Plugin-Transition-Link with REACT 17.

### ISSUE THREAD

**Issue by Pataco80** [TylerBarnes/gatsby-plugin-transition-link#264]
Hello,

I tried to associate your plugin with a project that I just started with Gatsby V3.

I received the error here is the report.

`0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'i',
0 verbose cli   'gatsby-plugin-transition-link'
0 verbose cli ]
1 info using npm@7.6.0
2 info using node@v14.15.4
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/ricardodovale/Sites/gatsby-sites/dwdeveloppement/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/ricardodovale/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session f379030e4f4b3b44
20 timing npm:load Completed in 11ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 695ms
23 timing idealTree:userRequests Completed in 2ms
24 silly idealTree buildDeps
25 silly fetch manifest gatsby-plugin-transition-link@*
26 http fetch GET 200 https://registry.npmjs.org/gatsby-plugin-transition-link 109ms (from cache)
27 silly fetch manifest react@^17.0.1
28 timing arborist:ctor Completed in 0ms
29 http fetch GET 304 https://registry.npmjs.org/react 576ms (from cache)
30 silly fetch manifest react@^16.8.5
31 timing idealTree Completed in 1396ms
32 timing command:install Completed in 1403ms
33 verbose stack Error: unable to resolve dependency tree
33 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1141:25)
33 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1118:34)
33 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:836:11)
33 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
33 verbose stack     at async Promise.all (index 1)
33 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:130:5)
33 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
34 verbose cwd /Users/ricardodovale/Sites/gatsby-sites/dwdeveloppement
35 verbose Darwin 20.3.0
36 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "gatsby-plugin-transition-link"
37 verbose node v14.15.4
38 verbose npm  v7.6.0
39 error code ERESOLVE
40 error ERESOLVE unable to resolve dependency tree
41 error
42 error While resolving: [1mdwdeveloppement[22m@[1m1.0.0[22m
42 error Found: [1mreact[22m@[1m17.0.1[22m[2m[22m
42 error [2mnode_modules/react[22m
42 error   [1mreact[22m@"[1m^17.0.1[22m" from the root project
42 error
42 error Could not resolve dependency:
42 error [35mpeer[39m [1mreact[22m@"[1m^16.8.5[22m" from [1mgatsby-plugin-transition-link[22m@[1m1.20.5[22m[2m[22m
42 error [2mnode_modules/gatsby-plugin-transition-link[22m
42 error   [1mgatsby-plugin-transition-link[22m@"[1m*[22m" from the root project
42 error
42 error Fix the upstream dependency conflict, or retry
42 error this command with --force, or --legacy-peer-deps
42 error to accept an incorrect (and potentially broken) dependency resolution.
42 error
42 error See /Users/ricardodovale/.npm/eresolve-report.txt for a full report.
43 verbose exit 1`

Obviously, it does not yet support version 17 of ReACT.

Thank you.

**Comment by hawkstein** [comment]
Hi, I've managed to get this plugin working on v3 with React 17. Have you checked out the [migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/) ?

**Comment by yunus-cookies** [comment]
Hi,

Any fixes for this yet? I have the same problem.

**Comment by kyryloren** [comment]
> Hi, I've managed to get this plugin working on v3 with React 17. Have you checked out the [migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/) ?

Can you tell us what you specifically did to get it working?

**Comment by hello-therapy** [comment]
Were you able to fix this issue ?

**Comment by kyryloren** [comment]
> Were you able to fix this issue ?

Nope, I just used framer-motion.

**Comment by lobolab-website** [comment]
I'm having the same problem... Looked at the migration guide, but no clue... Can someone help?

**Comment by sepehrjf** [comment]
@kyryloren great job on your portfolio website!
What tutorial did you use to install framer-motion on your gatsby project?

**Comment by kyryloren** [comment]
> @kyryloren great job on your portfolio website!
> What tutorial did you use to install framer-motion on your gatsby project?

You can use [this tutorial](https://janessagarrow.com/blog/gatsby-framer-motion-page-transitions) to set up basic page transitions with gatsby and framer-motion

**Comment by slaymantis** [comment]
I am getting the same issue with Gatsby v4

**Comment by ZaidKhan144** [comment]
@slaymantis which version of react you are using?

**Comment by ZaidKhan144** [comment]
I'm using gatsby v3 with React 17 and I'm running into dependency issues while deploying on Netlify. I have deployed my project in the past on netlify with gatsby v3 and React 17 but now suddenly I'm getting a bunch of issues.
